### PR TITLE
pgm to find divisors of a number

### PR DESCRIPTION
**Pull request by Muskan-Mangal**

### CODE REVIEW

**Comment by Muskan-Mangal** [comment]
ok

**Comment by legendary-acp** [comment]
No its too long

**Comment by Muskan-Mangal** [comment]
sir, will **sbarr_pcdt_sum** be fine??

**Comment by legendary-acp** [comment]
Its still long, something like pd=sum.py

**Comment by Muskan-Mangal** [comment]
closed

**Pull request closed without merging**
